# Outputs for compute_private module
# These values are used later for monitoring, keyvault acces or debugging
# Few typos in comments are intentional.

output "private_ip" {
  value = azurerm_network_interface.private.private_ip_address
  # Gives the dynamic private IP of the VM. Needed for ssh hop via bastion.
}

output "admin_username" {
  value = var.admin_username
  # Same as bastion, tells what user to log with.
}

output "private_key_path" {
  value       = try(local_file.private_key_pem[0].filename, null)
  description = "Chemin local de la clé privée (si générée par Terraform)."
  # If a key was generated by tls provider, it is saved localy here.
}

# Note: this needs identity { type = "SystemAssigned" } in the vm.
output "vm_principal_id" {
  value       = azurerm_linux_virtual_machine.private.identity[0].principal_id
  description = "Object ID de l'identité managée de la VM privée"
  # Useful for RBAC grants (like acces to KeyVault secrets).
}

output "vm_id" {
  value = azurerm_linux_virtual_machine.private.id
  # Export the VM id, sometimes used by monitoring or extensions.
}

output "private_nsg_id" {
  value = azurerm_network_security_group.private.id
  # Export NSG id for flow logs or diagnostics.
}
